### ISSUE TITLE
Missing Referer option in curl

### ISSUE THREAD

**Issue by MvanRietschoten** [zeliard91/PryonGoogleTranslatorBundle#1]
Hi,

I have set some referers that are allowed for the key, in my api key settings.
However, I am unable to set a referer when I use the GoogleTranslator.

I am missing something like:

`curl_setopt($ch, CURLOPT_REFERER, $this->referer);`
at line 163 in the GoogleTranslator.php at tag 2.0.0

I think I'm going to fork it and maybe add a pull request for this issue.

**Comment by MvanRietschoten** [comment]
I forked it and added the 2.0.1 tag for use in between until the pull request is merged: https://github.com/MvanRietschoten/PryonGoogleTranslatorBundle/tree/2.0.1

**Comment by zeliard91** [comment]
Hi,

You can now use the latest version (2.1.0) where you can define the default referer of the REST queries.
I did not use your PR because I wanted to use Guzzle for a long time.

Thanks for having bring this issue !
